### ISSUE TITLE
test failures with 5.22.0

### ISSUE THREAD

**Issue by jhi** [PerlDancer/Dancer2-Plugin-REST#10]
...
    Configuring Y/YA/YANICK/Dancer2-Plugin-REST-0.25.tar.gz with Build.PL
    Created MYMETA.yml and MYMETA.json
    Creating new 'Build' script for 'Dancer2-Plugin-REST' version '0.25'
      YANICK/Dancer2-Plugin-REST-0.25.tar.gz
      /usr/local/perl-forge/v/5.22.0/bin/perl Build.PL -- OK
    Running Build for Y/YA/YANICK/Dancer2-Plugin-REST-0.25.tar.gz
    Building Dancer2-Plugin-REST
      YANICK/Dancer2-Plugin-REST-0.25.tar.gz
      ./Build -- OK
    Running Build test
    t/00-compile.t ........................ ok
     #
    #
    # Generated by Dist::Zilla::Plugin::ReportVersions::Tiny v1.10
    # perl: 5.022000 (wanted 5.006) on linux from /usr/local/perl-forge/v/5.22.0/bin
    /perl
    #
    # Carp                                          => 1.36       (want any version)
    # Class::Load                                   => 0.23       (want any version)
    # Dancer2                                       => 0.161000   (want 0.149000_01)
    # Dancer2::Core::Request                        => 0.161000   (want any version)
    # Dancer2::Plugin                               => 0.161000   (want any version)
    # Data::Dumper                                  => 2.154      (want any version)
    # File::Spec                                    => 3.47       (want any version)
    # HTTP::Request::Common                         => 6.10       (want any version)
    # IO::Handle                                    => 1.28       (want any version)
    # IPC::Open3                                    => 1.18       (want any version)
    # JSON                                          => 2.90       (want any version)
    # Module::Build                                 => 0.4214     (want 0.28)
    # Module::Runtime                               => 0.014      (want any version)
    # Moo::Role                                     => 2.000002   (want any version)
    # Plack::Test                                   => <undef>    (want any version)
    # Test::More                                    => 1.001014   (want 0.88)
    # strict                                        => 1.09       (want any version)
    # warnings                                      => 1.32       (want any version)
    #
    # Thanks for using my code.  I hope it works for you.
    # If not, please try and include this output in the bug report.
    # That will help me reproduce the issue and solve your problem.
    #
    t/000-report-versions-tiny.t .......... ok

    #   Failed test 'headers have content_type set to (?^:text/html)'
    #   at t/02_prepare_serializer_for_format.t line 71.
    #                   'text/x-yaml'
    #     doesn't match '(?^:text/html)'

    #   Failed test '$data has been encoded'
    #   at t/02_prepare_serializer_for_format.t line 73.
    #          got: '--- root
    # '
    #     expected: 'root'
    # Looks like you failed 2 tests of 10.
    t/02_prepare_serializer_for_format.t ..
    Dubious, test returned 2 (wstat 512, 0x200)
    Failed 2/10 subtests
    t/03_resource.t ....................... ok
    t/04_helpers.t ........................ ok
    [Webservice:722] core @2015-08-20 23:12:28> Failed to serialize the request: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /usr/local/perl-forge/v/5.22.0/site/lib/JSON.pm line 154. in (eval 142) l. 1

    #   Failed test 'response looks good for 'GET /''
    #   at t/04_plugin_settings.t line 68.
    #          got: ''
    #     expected: 'root'

    #   Failed test 'response looks good for 'GET /''
    #   at t/04_plugin_settings.t line 68.
    #          got: '--- root
    # '
    #     expected: 'root'
    # Looks like you failed 2 tests of 5.
    t/04_plugin_settings.t ................
    Dubious, test returned 2 (wstat 512, 0x200)
    Failed 2/5 subtests

    #   Failed test 'headers have content_type set to (?^:text/html)'
    #   at t/05_named_captures.t line 64.
    #                   'text/x-yaml'
    #     doesn't match '(?^:text/html)'

    #   Failed test '$data has been encoded'
    #   at t/05_named_captures.t line 67.
    #          got: '--- root
    # '
    #     expected: 'root'
    # Looks like you failed 2 tests of 8.
    t/05_named_captures.t .................
    Dubious, test returned 2 (wstat 512, 0x200)
    Failed 2/8 subtests
    t/06_tcp_server.t ..................... ok

    Test Summary Report
    -------------------
    t/02_prepare_serializer_for_format.t (Wstat: 512 Tests: 10 Failed: 2)
      Failed tests:  9-10
      Non-zero exit status: 2
    t/04_plugin_settings.t              (Wstat: 512 Tests: 5 Failed: 2)
      Failed tests:  1, 5
      Non-zero exit status: 2
    t/05_named_captures.t               (Wstat: 512 Tests: 8 Failed: 2)
      Failed tests:  7-8
      Non-zero exit status: 2
    Files=8, Tests=50,  4 wallclock secs ( 0.08 usr  0.02 sys +  3.44 cusr  0.36 csys =  3.90 CPU)
    Result: FAIL
    Failed 3/8 test programs. 6/50 subtests failed.
      YANICK/Dancer2-Plugin-REST-0.25.tar.gz
      ./Build test -- NOT OK

**Comment by yanick** [comment]
should be fixed in master
