### ISSUE TITLE
Dancer2-Plugin-REST-1.02 from CPAN test fails under perl v5.16.3

### ISSUE THREAD

**Issue by bolangi** [PerlDancer/Dancer2-Plugin-REST#17]
Dear Maintainer,

This is a self-compiled v5.16.3, installed via perlbrew. The OS is Ubuntu Trusty Tahr.
I note that the version number was not found for Plack::Test.

Thank you

---- build.log ----

    cpanm (App::cpanminus) 1.6911 on perl 5.016003 built for x86_64-linux
    Work directory is /home/childspace/.cpanm/work/1511817009.5149
    You have make /usr/bin/make
    You have LWP 6.06
    You have /bin/tar: tar (GNU tar) 1.27.1
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Written by John Gilmore and Jay Fenlason.
    You have /usr/bin/unzip
    Searching Dancer2::Plugin::REST on cpanmetadb ...
    --> Working on Dancer2::Plugin::REST
    Fetching http://www.cpan.org/authors/id/Y/YA/YANICK/Dancer2-Plugin-REST-1.02.tar.gz
    -> OK
    Unpacking Dancer2-Plugin-REST-1.02.tar.gz
    Entering Dancer2-Plugin-REST-1.02
    Checking configure dependencies from META.json
    Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.30)
    Configuring Dancer2-Plugin-REST-1.02
    Running Makefile.PL
    Checking if your kit is complete...
    Looks good
    Generating a Unix-style Makefile
    Writing Makefile for Dancer2::Plugin::REST
    Writing MYMETA.yml and MYMETA.json
    -> OK
    Checking dependencies from MYMETA.json ...
    Checking if you have Test::Requires 0 ... Yes (0.07)
    Checking if you have File::Spec 0 ... Yes (3.39_02)
    Checking if you have IO::Handle 0 ... Yes (1.33)
    Checking if you have Dancer2::Serializer::Mutable 0 ... Yes (0.205002)
    Checking if you have Module::Runtime 0 ... Yes (0.014)
    Checking if you have IPC::Open3 0 ... Yes (1.12)
    Checking if you have List::Util 0 ... Yes (1.49)
    Checking if you have Plack::Test 0 ... Yes (undef)
    Checking if you have Dancer2 0.203000 ... Yes (0.205002)
    Checking if you have Dancer2::Plugin 0 ... Yes (0.205002)
    Checking if you have warnings 0 ... Yes (1.13)
    Checking if you have Dancer2::Core::HTTP 0.203000 ... Yes (0.205002)
    Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.30)
    Checking if you have Data::Dumper 0 ... Yes (2.135_06)
    Checking if you have Moo 0 ... Yes (2.003003)
    Checking if you have HTTP::Request::Common 0 ... Yes (6.04)
    Checking if you have Carp 0 ... Yes (1.26)
    Checking if you have Test::More 0 ... Yes (0.98)
    Checking if you have strict 0 ... Yes (1.07)
    Checking if you have Dancer2::Core::Request 0 ... Yes (0.205002)
    Checking if you have JSON 0 ... Yes (2.97000)
    Building and testing Dancer2-Plugin-REST-1.02
    cp lib/Dancer2/Plugin/REST.pm blib/lib/Dancer2/Plugin/REST.pm
    Manifying 1 pod document
    PERL_DL_NONLAZY=1 "/home/childspace/perl5/perlbrew/perls/perl-5.16.3/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
    t/00-compile.t ........................ ok
    #
    # Versions for all modules listed in MYMETA.json (including optional ones):
    #
    # === Configure Requires ===
    #
    #     Module              Want Have
    #     ------------------- ---- ----
    #     ExtUtils::MakeMaker  any 7.30
    #
    # === Build Requires ===
    #
    #     Module              Want Have
    #     ------------------- ---- ----
    #     ExtUtils::MakeMaker  any 7.30
    #
    # === Test Requires ===
    #
    #     Module                     Want     Have
    #     ---------------------- -------- --------
    #     Dancer2                0.203000 0.205002
    #     Dancer2::Core::Request      any 0.205002
    #     Data::Dumper                any 2.135_06
    #     ExtUtils::MakeMaker         any     7.30
    #     File::Spec                  any  3.39_02
    #     HTTP::Request::Common       any     6.04
    #     IO::Handle                  any     1.33
    #     IPC::Open3                  any     1.12
    #     JSON                        any  2.97000
    #     Module::Runtime             any    0.014
    #     Plack::Test                 any    undef
    #     Test::More                  any     0.98
    #     Test::Requires              any     0.07
    #
    # === Test Recommends ===
    #
    #     Module         Want     Have
    #     ---------- -------- --------
    #     CPAN::Meta 2.120900 2.143240
    #
    # === Runtime Requires ===
    #
    #     Module                           Want     Have
    #     ---------------------------- -------- --------
    #     Carp                              any     1.26
    #     Dancer2                      0.203000 0.205002
    #     Dancer2::Core::HTTP          0.203000 0.205002
    #     Dancer2::Plugin                   any 0.205002
    #     Dancer2::Serializer::Mutable      any 0.205002
    #     List::Util                        any     1.49
    #     Moo                               any 2.003003
    #     strict                            any     1.07
    #     warnings                          any     1.13
    #
    t/00-report-prereqs.t ................. ok
    Can't call method "scheme" on an undefined value at /home/childspace/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/Plack/Test/MockHTTP.pm line 19.
        # Child ((?^:text/html)) exited without calling finalize()
    
    #   Failed test '(?^:text/html)'
    #   at /home/childspace/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3/Test/Builder.pm line 252.
    # Looks like you planned 6 tests but ran 1.
    # Looks like you failed 1 test of 1 run.
    # Looks like your test exited with 29 just after 1.
    t/02_prepare_serializer_for_format.t ..
    Dubious, test returned 29 (wstat 7424, 0x1d00)
    Failed 6/6 subtests
    t/03_resource.t ....................... ok
    t/04_helpers.t ........................ ok
    t/04_plugin_settings.t ................ ok
    t/05_named_captures.t ................. ok
    t/06_tcp_server.t ..................... ok
    
        #   Failed test 'Got app'
        #   at t/gh14-deserialized.t line 47.
        #          got: ''
        #     expected: 'CODE'
    Use of uninitialized value in subroutine entry at /home/childspace/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/Plack/Test/MockHTTP.pm line 24.
    Use of uninitialized value in subroutine entry at /home/childspace/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/Plack/Test/MockHTTP.pm line 24.
    
        #   Failed test '[POST: Check Name  ] '
        #   at t/gh14-deserialized.t line 51.
        #          got: '500'
        #     expected: '200'
    malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "Can't use string (""...") at /home/childspace/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/JSON.pm line 187.
        # Child ($restapp) exited without calling finalize()
    
    #   Failed test '$restapp'
    #   at /home/childspace/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3/Test/Builder.pm line 252.
    # Tests were run but no plan was declared and done_testing() was not seen.
    t/gh14-deserialized.t .................
    Dubious, test returned 255 (wstat 65280, 0xff00)
    Failed 1/1 subtests
    
    Test Summary Report
    -------------------
    t/02_prepare_serializer_for_format.t (Wstat: 7424 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 29
      Parse errors: Bad plan.  You planned 6 tests but ran 1.
    t/gh14-deserialized.t               (Wstat: 65280 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 255
      Parse errors: No plan found in TAP output
    Files=9, Tests=38, 15 wallclock secs ( 0.12 usr  0.05 sys + 13.33 cusr  0.81 csys = 14.31 CPU)
    Result: FAIL
    Failed 2/9 test programs. 2/38 subtests failed.
    make: *** [test_dynamic] Error 255
    -> FAIL Installing Dancer2::Plugin::REST failed. See /home/childspace/.cpanm/build.log for details.

**Comment by yanick** [comment]
I did a clean install of 5.16.3, and installed Dancer2::Plugin::REST straight on it and... it works for me. And looking at the CPAN tester reports, it seems that the tests are green everywhere. Unfortunately, right now it looks like the problem is on your side. :-/

**Comment by bolangi** [comment]
Thank you for the trouble of testing. It appears to be a spurious result. I am closing this ticket.
