### ISSUE TITLE
status_not_found and friends not properly serialized

### ISSUE THREAD

**Issue by yanick** [PerlDancer/Dancer2-Plugin-REST#18]
For error codes, we return `hashXXXXX` instead of the serialized content.

**Comment by yanick** [comment]
@cromedome  Uuh... I added a test, and it... works for me? O.o 

https://github.com/PerlDancer/Dancer2-Plugin-REST/compare/master...PerlDancer:serialize-error?expand=1

**Comment by cromedome** [comment]
Missing:
`set serializer => 'JSON';`
Closing.
