### ISSUE TITLE
Test suite started to fail (new one)

### ISSUE THREAD

**Issue by eserte** [PerlDancer/Dancer2-Plugin-REST#5]
See http://matrix.cpantesters.org/?dist=Dancer2-Plugin-REST;reports=1#sl=7,1 for a time-sorted overview. This time it starts to fail from Nov 15.

**Comment by eserte** [comment]
http://analysis.cpantesters.org/reports_by_field?distv=Dancer2-Plugin-REST-0.25;field=mod%3ADancer2 suggests that the failure is caused by Dancer2 0.154000 and later.

**Comment by emil-perhinschi** [comment]
the last set serializer survives across requests so Dancer2-Plugin-REST/t/02_prepare_serializer_for_format.t fails when processing the last

    {
        path => '/',
        content_type => qr'text/html',
        response => 'root',
    }

**Comment by qrovira** [comment]
Just ftr, this issue was solved a year ago with 64ca438.
