### ISSUE TITLE
charset missing in content-type

### ISSUE THREAD

**Issue by LittleFox94** [PerlDancer/Dancer2-Plugin-REST#7]
The charset is missing in the content-type, giving me encoding problems as I use UTF-8 encoded text.
Would you please add the charset configured for the app? Thanks

**Comment by LittleFox94** [comment]
I've reported the issue here, as the original repository is older and seems to be no longer active.

**Comment by emil-perhinschi** [comment]
have you set the charset in Dancer2 ?

http://search.cpan.org/~sukria/Dancer2-0.03/lib/Dancer2/Config.pod#charset_%28string%29

**Comment by LittleFox94** [comment]
Yes, it is set:
```charset: "UTF-8"```

**Comment by emil-perhinschi** [comment]
I'll look at it

I'm not related to the project but I started fixing the plugin because somebody at work needed it working and the tests failed with the latest Dancer2 version; I guess the charset question will come sooner or later :)

**Comment by emil-perhinschi** [comment]
it looks like application/json should be UTF-* by default and no "charset" should be specified http://www.iana.org/assignments/media-types/application/json

yaml also should be UTF-8 or UTF-16 http://yaml.org/spec/current.html#id2513160 

so "charset" is not needed

**Comment by LittleFox94** [comment]
Hm.. I saw this problem when browsing to a REST-route in chrome ... so this is actually a chrome bug?

**Comment by emil-perhinschi** [comment]
... don't know about Chrome 

maybe there was a non-UTF-8 or a non-printable character in the data ?

**Comment by dolmen** [comment]
Are you sure you don't have encoding problems in your source data?

If you the issue is really in the ouput, a reproducible test case would help...

**Comment by LittleFox94** [comment]
I'll check my source data and come back here.

**Comment by LittleFox94** [comment]
You were right, the problems were from the source data (incorrect usage of Net::LDAP).
Thank you for the hint and sorry for bothering.
